### ISSUE TITLE
implicit transform un-fitted tokens and update internal labels

### ISSUE THREAD

**Issue by chengweitsai** [Dobatymo/encoders#1]
The fitted encoder implicit transform un-fitted tokens, instead of raising a ValueError.

<img width="333" alt="Screen Shot 2022-01-03 at 6 42 53 PM" src="https://user-images.githubusercontent.com/17897129/147921851-54310d94-ee16-4183-b0ce-8059d55ff364.png">

**Comment by Dobatymo** [comment]
Fixed here https://github.com/Dobatymo/encoders/commit/42a8c472d8bdeffa9aa98af23f2e677fe9b705e5
`transform` raises an IndexError on unknown tokens now. Currently doesn't build on windows though...
